### ISSUE TITLE
Change name of CI job.

### ISSUE THREAD

**Issue by floooh** [kassane/sokol-d#16]
One last request :)

Can you change the name of the CI build here to somehing like `D` or `Dlang`?

https://github.com/kassane/sokol-d/blob/0b2587fa619be83d7cde1b572926a4b0d4c685aa/.github/workflows/build.yml#L1

It would then be consistent with the other language bindings in the sokol readme badges stripe:

<img width="714" alt="image" src="https://github.com/kassane/sokol-d/assets/1699414/63dff1eb-a31a-4f10-9be2-75e9ee0c63f6">

...unfortunately I can't override the text in the badge on my own, it takes the name of the CI job.

**Comment by floooh** [comment]
PS: I think you can also remove the `[unofficial]` now from the Github repo description ;)

**Comment by kassane** [comment]
> PS: I think you can also remove the `[unofficial]` now from the Github repo description ;)

Done.

**Comment by floooh** [comment]
Looking good, thanks!

<img width="105" alt="image" src="https://github.com/kassane/sokol-d/assets/1699414/496c655d-77fd-4c87-9bc7-84d530c4a55b">
