### ISSUE TITLE
Weird problem after removing SG_FILTER_NONE in sokol_imgui.h

### ISSUE THREAD

**Issue by floooh** [kassane/sokol-d#25]
...so this is weird: I removed `SG_FILTER_NONE` in sokol_gfx.h which also caused changes in sokol_imgui.h. But the change in sokol_imgui.h isn't picked up in the automatic sokol-d bindings generation, causing CI to fail:

https://github.com/kassane/sokol-d/actions/runs/10667398346

E.g. the file https://github.com/kassane/sokol-d/blob/main/src/sokol/c/sokol_imgui.h hasn't been updated, and this line

https://github.com/kassane/sokol-d/blob/c686db871a6d3a289cb3c461cdfb5b42d44a7f29/src/sokol/c/sokol_imgui.h#L2403

...should have been changed.

Investigating...

**Comment by floooh** [comment]
...blargh it doesn't work out of the box to simply add sokol_imgui.h, e.g. when running `python3 gen_all.py`:

```
sokol-d/src/sokol/c/sokol_imgui.c:8:10: fatal error: 'cimgui.h' file not found
#include "cimgui.h"
         ^~~~~~~~~~
```

...I think the file

https://github.com/kassane/sokol-d/blob/main/src/sokol/c/sokol_imgui.c

...needs to be changed like this:

https://github.com/floooh/sokol-zig/blob/master/src/sokol/c/sokol_imgui.c

(e.g. cimgui.h only be included in the implementation block)

...let me try that fix too...

**Comment by kassane** [comment]
> Apologies for committing directly to main.

@floooh,

No worries!
Please feel free to make any changes, including to `build.zig` (replacing `[]const u8` to `LazyPath` on ldc2 buildStep).

Thank you for help.

**Comment by floooh** [comment]
Ok all done, this is the change in the sokol main repo:

https://github.com/floooh/sokol/commit/df71cc24cb273c0cf68ccef91932c09893006b18

...but as expected this didn't trigger a commit to the sokol-d repo.

Cheers!
