### ISSUE TITLE
Replace kassane/cimgui to cimgui-upstream

### ISSUE THREAD

**Issue by floooh** [kassane/sokol-d#26]
Hi @kassane, quick heads up: I just updated sokol_imgui.h to be compatible to cimgui 1.91.1 (see: https://github.com/floooh/sokol/commit/1eb96dd0f96b9ea73065f9078244c2255c2b75d9).

This broke the sokol-d build because that was still on older ImGui/cimgui versions.

For now I updated the sokol-d build.zig.zon to Dear ImGui and cimgui 1.91.1, which at least makes the build go green again.

**BUT:**

I temporarily changed the cimgui URL in build.zig.zon from your fork at git+https://github.com/kassane/cimgui to the main cimgui URL.

This ticket only as reminder for you to move the build.zig.zon URL back to your fork after you merged the 1.91.1 upstream changes.

What are the changes in your cimgui fork btw?

**Comment by floooh** [comment]
PS: hmm strange the CI is still broken because imgui.h can't be found (I guess changing the include path was one of your changes?):

```
/Users/runner/.cache/zig/p/122067e25fdf4d7117ba3de74d6403d61cd5c9c783b7eae974038132eb97f4ff1609/cimgui.cpp:13:10: error: './imgui/imgui.h' file not found
error: warning(compilation): failed to delete '/Users/runner/work/sokol-d/sokol-d/.zig-cache/tmp/2a968442805d3bfd-cimgui.o.d': FileNotFound
```

...it's strange because the build works on my local machine, hmm...

**Comment by floooh** [comment]
Ok, in the sokol-zig-imgui-sample project that same project is solved by copying the cimgui and imgui files to bring them into the expected directory structure:

https://github.com/floooh/sokol-zig-imgui-sample/blob/2597832beb515cf282189422d6fa4e84c8daa0b9/deps/cimgui/build.zig#L11-L15

...maybe also an idea for sokol-d?

**Comment by kassane** [comment]
Based your latest test. `b.WriteFiles` works in `fn build` ('main' zig-build) only or add preview step - sadly zig-build no add pos/after-steps.
Now, my currently test add `b.addInstallDirectory`, works (no-tmpdir): https://github.com/kassane/sokol-d/commit/94a76b3b7a9785c17f1e2417b2b81194a7c53680
