### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kassane** [kassane/sokol-d#3]
- [x] #2
- [x] #1
- [x] #4
- [x] #5 
- [x] #6 
- [x] #10 
- [x] #7 
- [x] #9 
- [x] #13
- [x] #19 
- [x] #21 
- [ ] ~~Documentation~~ (autogenerated code does not keep comments)
- [x] Get D packages(s) with zig-pkg (zon)

### External Reference

- https://github.com/floooh/sokol/pull/955

**Comment by kassane** [comment]
### Improvement LDC support

- https://github.com/dlang/dub/pull/2660

**Comment by kassane** [comment]
Based on some information, it is expected to improve support for nogc and/or betterC.
Currently the `user_data` example requires GC because of AA (associative array)

- https://github.com/al1-ce/clib/issues/8

**Comment by kassane** [comment]
## Improvement wasm support

The latest changes are intended to remove support for **custom-Druntime** (obsolete and incomplete). Only *wasm32-target* as **betterC** will be allowed. #20 
This needs to be re-tested and improved.

However, for a higher priority, it is still necessary to resolve the linking conflicts of the objects generated by **ldmd2/ldc2** 

**Note:** **ldmd2** is just the wrapper for the **ldc2** compiler, using the **dmd** flags (`ldc2 -ldmd` - w/ dmd library).

### Building wasm-target involves what steps?

#### Four steps (current)

- libsokol build
- Build an object with **ldc2** (not an executable or library). [`wasm32-unknown-unknwon-wasm` is `wasm32-freestanding`]
   - `wasm-unknown-emscripten` get `Warning: unknown target OS: emscripten`
- Capture the previously built object and use **zig** to re-address the object references. [`wasm32-emscripten`]
- Get the object to **emcc**. It will generate the final binary (`*.wasm`). [`wasm32-unknown-emscripten`]

### Build tests

In the following, I have tested it manually (no zig build system).

- **ldc + emcc** - same steps

<details>
<summary>ldc2-wasm (manual build-test)</summary>

```bash
# sokol-d path == pwd

$ mkdir $PWD/build
$ ldc2 -ldmd -c -w -preview=all -Oz -release -enable-inlining -boundscheck=off -vcolumns -od=$PWD/build -cache=/home/kassane/sokol-d/zig-cache/o/27f92344914739129514f9188caf365b -oq -disable-verify -Hkeep-all-bodies -i -I/home/kassane/sokol-d/src /home/kassane/sokol-d/src/examples/clear.d --d-version=CarelessAlocation -L-allow-undefined -Xcc=-v -P-I/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/include -Xcc=-DIMPL -Xcc=-DSOKOL_GLES3 -mtriple=wasm32-unknown-unknown-wasm /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a -flto=thin

$ tree build
build
└── examples.clear.o

1 directory, 1 file

$ mkdir $PWD/build/web
$ $HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/emcc -sASSERTIONS=0 -Oz -flto --closure 1 -sUSE_WEBGL2=1 -sNO_FILESYSTEM=1 -sMALLOC='emmalloc' --shell-file=src/sokol/web/shell.html -o$PWD/build/web/clear.html -sUSE_OFFSET_CONVERTER=1 $PWD/build/examples.clear.o /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a 
wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libGL-webgl2-getprocaddr.a(webgl1.o at 11618)' is 'wasm32-unknown-emscripten' whereas 'ld-temp.o' is 'wasm32-unknown-unknown-wasm'

wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(abort.o at 342416)' is 'wasm32-unknown-emscripten' whereas 'ld-temp.o' is 'wasm32-unknown-unknown-wasm'

wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(library_pthread_stub.o at 2939600)' is 'wasm32-unknown-emscripten' whereas 'ld-temp.o' is 'wasm32-unknown-unknown-wasm'

wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(roundf.o at 4345288)' is 'wasm32-unknown-emscripten' whereas 'ld-temp.o' is 'wasm32-unknown-unknown-wasm'
# [...] SKIP (SAME warnings)
$ tree build
build
├── examples.clear.o
└── web
    ├── clear.html
    ├── clear.js
    └── clear.wasm

2 directories, 4 files
```
**Output:** Black screen!! :cry:  
</details>

- **ldc + zig + emcc**

<details>
<summary>ldc2-wasm (manual build-test)</summary>

```bash
$ ldmd2 -c -w -preview=all -Oz -release -enable-inlining -boundscheck=off -vcolumns -od=$PWD/build -oq -disable-verify -Hkeep-all-bodies -i -I$HOME/sokol-d/src $HOME/sokol-d/src/examples/clear.d -L-allow-undefined -Xcc=-v -P-I$HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/include -Xcc=-DIMPL -Xcc=-DSOKOL_GLES3 -mtriple=wasm32-unknown-unknown-wasm $HOME/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a

$ zig build-obj $PWD/build/examples.clear.o /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a -OReleaseSmall -target wasm32-emscripten -mcpu baseline -I /home/kassane/sokol-d/zig-cache/o/6f5a8a62c22680ad92a78d948ac77f24 -lc --name clear -femit-bin=$PWD/build/clear.o -static

$ tree build
build
├── clear.o
├── examples.clear.o
└── web
 $HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/emcc -sASSERTIONS=0 -Oz -flto --closure 1 -sUSE_WEBGL2=1 -sNO_FILESYSTEM=1 -sMALLOC='emmalloc' --shell-file=src/sokol/web/shell.html -o$PWD/build/web/clear.html -sUSE_OFFSET_CONVERTER=1 $PWD/build/clear.o $HOME/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a
wasm-ld: warning: function signature mismatch: sg_make_shader
>>> defined as (i32, i32) -> void in /home/kassane/sokol-d/build/clear.o
>>> defined as (i32) -> i32 in /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a(/home/kassane/sokol-d/zig-cache/o/54cced09d05b5ad8e831190d0960f355/sokol_gfx.o)

wasm-ld: warning: function signature mismatch: sg_make_buffer
>>> defined as (i32, i32) -> void in /home/kassane/sokol-d/build/clear.o
>>> defined as (i32) -> i32 in /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a(/home/kassane/sokol-d/zig-cache/o/54cced09d05b5ad8e831190d0960f355/sokol_gfx.o)

wasm-ld: warning: function signature mismatch: sg_gl_query_shader_info
>>> defined as (i32, i32) -> void in /home/kassane/sokol-d/build/clear.o
>>> defined as (i32) -> i32 in /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a(/home/kassane/sokol-d/zig-cache/o/54cced09d05b5ad8e831190d0960f355/sokol_gfx.o)

wasm-ld: warning: function signature mismatch: sg_d3d11_query_sampler_info
>>> defined as (i32, i32) -> void in /home/kassane/sokol-d/build/clear.o
>>> defined as (i32) -> i32 in /home/kassane/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a(/home/kassane/sokol-d/zig-cache/o/54cced09d05b5ad8e831190d0960f355/sokol_gfx.o)
# [...] SKIP (same warnings)
$ tree build
build
├── clear.o
├── examples.clear.o
└── web
    ├── clear.html
    ├── clear.js
    └── clear.wasm

2 directories, 5 files
```
**Output:** Works :partying_face: 
</details>

- **ldc + emcc** - embedded

<details>
<summary>ldc2-wasm (manual build-test)</summary>

```bash
# sokol-d path == pwd
$ mkdir -p build/web
$ ldmd2 -c -w -preview=all -Oz -release -enable-inlining -boundscheck=off -vcolumns -od=$PWD/build -oq -disable-verify -Hkeep-all-bodies -i -I$HOME/sokol-d/src $HOME/sokol-d/src/examples/clear.d -L-allow-undefined -Xcc=-v -P-I$HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/include -Xcc=-DIMPL -Xcc=-DSOKOL_GLES3 -mtriple=wasm32-unknown-unknown-wasm $HOME/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a -gcc=$HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/emcc --linker=$HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/emcc -P-sASSERTIONS=0 -Xcc=-Oz -Xcc="--closure 1" -P-sUSE_WEBGL2=1 -P-sNO_FILESYSTEM=1 -P-sMALLOC='emmalloc' -Xcc=--shell-file=src/sokol/web/shell.html -Xcc=-o$PWD/build/web/clear.html -P-sUSE_OFFSET_CONVERTER=1 -flto=full

$ $HOME/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/emcc -sASSERTIONS=0 -Oz --closure 1 -sUSE_WEBGL2=1 -sNO_FILESYSTEM=1 -sMALLOC='emmalloc' --shell-file=src/sokol/web/shell.html -o$PWD/build/web/clear.html -sUSE_OFFSET_CONVERTER=1 $PWD/build/examples.clear.o $HOME/sokol-d/zig-cache/o/e35346434b3113a9d28288ab4edc2b5d/libsokol.a
# [...] *NO Warnings*
$ tree build
build
├── clear.o
├── examples.clear.o
└── web
    ├── clear.html
    ├── clear.js
    └── clear.wasm

2 directories, 5 files
```
**Output:** Works :partying_face: 
</details>

**Note 2:** LTO between **ldc2** and **emcc** cause warnings. Prefer enable LTO in ldc2 only (no or minimum warnings)!!
```bash
wasm-ld: warning: Linking two modules of different data layouts: '/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(llrintl.o at 2994444)' is 'e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-f128:64-n32:64-S128-ni:1:10:20' whereas 'ld-temp.o' is 'e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-n32:64-S128-ni:1:10:20'
```

cc: @floooh

**Comment by floooh** [comment]
Just FIY, I'll be travelling until Thursday and will probably be unresponsive during that time.

**Comment by kassane** [comment]
> Just FIY, I'll be travelling until Thursday and will probably be unresponsive during that time.

No trouble! Enjoy your travels.

---

> Note 2: LTO between ldc2 and emcc cause warnings. Prefer enable LTO in ldc2 only (no or minimum warnings)!!

After fix ldc2 (master) issue (add `wasm32-unknwon-emscripten`)... 
I have discovered a strange situation, in that when enabling LTO on all in release mode. 
```bash
warning: Linking two modules of different target triples: '/home/kassane/sokol-d/zig-cache/o/11f2f18f48ea24e538f790ad4c0e12f8/libsokol.a(sokol_gfx.o at 101382)' is 'wasm32-unknown-emscripten-musl' whereas 'ld-temp.o' is 'wasm32-unknown-emscripten'
```
The issue is fixed (without warnings) when passing `-Dtarget=wasm32-emscripten-none`.

**Comment by kassane** [comment]
After new updates and the possible inclusion of **imgui** support. As you can see, `build.zig` is quite long and complicated.

Unlike the [sokol-zig](https://github.com/floooh/sokol-zig) approach (by @floooh), sokol-d has everything included, which requires extending the support in `build.zig`.
So far, the port of [pacman.c](https://github.com/floooh/pacman.c)/[pacman.zig](https://github.com/floooh/pacman.zig) to [pacman.d](https://github.com/kassane/pacman.d) is in progress, as a first external solution using **sokol-d**.

Any suggestions for other approaches to reduce such complexity?

Maybe **pacman.d** can serve as a reference.

**Comment by kassane** [comment]
- After some testing with zig-master regarding external package management, I will need to postpone porting the build system modularization
- Also, it requires looking into the issues with shaded examples in wasm32, while knowing ldc2's poor support for the target.
- Also evaluate the possibility of updating imgui support (replacing cimgui to [dear-bindings](https://github.com/dearimgui/dear_bindings)).
- Another alternative to try is to add nuklear support.

**Comment by kassane** [comment]
The next ldc2 version brings improved `wasm32-emscripten-musl` support.

> Emscripten: The compiler now mimicks a musl Linux platform wrt. extra predefined versions.

**More info:** https://forum.dlang.org/post/xmrqpocmcfwpajxvzfal@forum.dlang.org

---

Remeber: Currently, the wasm32 target in this project has LTO enabled (ldc2/zig cc/emcc) in release mode.

However, `wasm32-emscripten` and `wasm32-wasi` in Zig links musl-libc by default. Causing conflict on the part of the object generated by ldc2 and `sokol` library. Add `-none` in wasm triple-target to bypass linker error.

This compiler improvement, it might help linking with musl-libc on LTO enabled. In debug mode (LTO off) emit warnings yet!

**Comment by kassane** [comment]
**Previous test**
> **Note 2:** LTO between **ldc2** and **emcc** cause warnings. Prefer enable LTO in ldc2 only (no or minimum warnings)!!
> ```bash
> wasm-ld: warning: Linking two modules of different data layouts: '/home/kassane/.cache/zig/p/122083537ec3463ee4b2d520bf86a36b1057ab05abfe712c32bae1048f9b0c6e2a13/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto/libc.a(llrintl.o at 2994444)' is 'e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-f128:64-n32:64-S128-ni:1:10:20' whereas 'ld-temp.o' is 'e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-n32:64-S128-ni:1:10:20'
> ```

> The next ldc2 version brings improved `wasm32-emscripten-musl` support.
>> Emscripten: The compiler now mimicks a musl Linux platform wrt. extra predefined versions.

```bash
$ zig build run-clear -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall
run-clear
└─ run /home/kassane/.cache/zig/p/1220146d92ca77f3cabb151fd035f6fa2ea03481ea07f3358ec912f17acdba791a8a/upstream/emscripten/emrun
   └─ install generated/
      └─ emcc stderr
wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/sokol-d/.zig-cache/o/10eb24f94f096a2b4bc05693912b8a55/libsokol.a(sokol_log.o at 11906)' is 'wasm32-unknown-emscripten-musl' whereas 'ld-temp.o' is 'wasm32-unknown-emscripten'
wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/sokol-d/.zig-cache/o/10eb24f94f096a2b4bc05693912b8a55/libsokol.a(sokol_app.o at 20434)' is 'wasm32-unknown-emscripten-musl' whereas 'ld-temp.o' is 'wasm32-unknown-emscripten'
wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/sokol-d/.zig-cache/o/10eb24f94f096a2b4bc05693912b8a55/libsokol.a(sokol_gfx.o at 95426)' is 'wasm32-unknown-emscripten-musl' whereas 'ld-temp.o' is 'wasm32-unknown-emscripten'
wasm-ld: warning: Linking two modules of different target triples: '/home/kassane/sokol-d/.zig-cache/o/10eb24f94f096a2b4bc05693912b8a55/libsokol.a(sokol_glue.o at 404594)' is 'wasm32-unknown-emscripten-musl' whereas 'ld-temp.o' is 'wasm32-unknown-emscripten'
```

`ldc2` + `emcc` (LTO enabled) no have different target triples.
